/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.Atributo;
import CLASES.Entidad;
import DATA.DataImportar;
import LOGICA.BLAtributo;
import LOGICA.BLImportarData;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class GUIImportarData extends javax.swing.JFrame {
    JFileChooser SelectArchivo=new JFileChooser();
    File archivo;
    DataImportar objDataImportar = new DataImportar();
    BLImportarData objBLImportarData = new BLImportarData();
    BLAtributo objBLAtributo = new BLAtributo();
    Entidad objAuxEntidad = new Entidad();
    ArrayList<Atributo> arrayClavesPrimarias = new ArrayList<>();
    ArrayList<Atributo> arrayClavesCandidatas = new ArrayList<>();
    int numClavesCandidatas = 0;
    int numClavesPrimarias = 0;
    Entidad objEntidad = new Entidad();

    /**
     * Creates new form GUIImportarData
     */
    public GUIImportarData() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUniversal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnImportar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonElegir = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableClavesCandidatas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableClavesPrimarias = new javax.swing.JTable();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelEntidadUniversal = new javax.swing.JLabel();
        jTextFieldNombreEntidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableUniversal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableUniversal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 930, 130));

        jLabel1.setText("Claves Primarias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 20));

        btnImportar.setText("Importar Datos");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnImportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 169, 50));

        jLabel2.setText("Claves Candidatas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        jButtonElegir.setText("Elegir -->");
        jButtonElegir.setEnabled(false);
        jButtonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElegirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 140, -1));

        jButtonEliminar.setText("<-- Eliminar");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 140, -1));

        jTableClavesCandidatas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClavesCandidatas.setEnabled(false);
        jScrollPane4.setViewportView(jTableClavesCandidatas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, 140));

        jTableClavesPrimarias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClavesPrimarias.setEnabled(false);
        jScrollPane5.setViewportView(jTableClavesPrimarias);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 130, 140));

        jButtonSiguiente.setText("Siguiente -->");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 515, -1, 30));

        jLabelEntidadUniversal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelEntidadUniversal.setText("TABLA UNIVERSAL");
        getContentPane().add(jLabelEntidadUniversal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 330, 40));

        jTextFieldNombreEntidad.setEnabled(false);
        getContentPane().add(jTextFieldNombreEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 72, 180, 30));

        jLabel3.setText("Nombre de entidad: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:
        if(SelectArchivo.showDialog(null, "Seleccionar Archivo")==JFileChooser.APPROVE_OPTION){
                archivo=SelectArchivo.getSelectedFile();
                //ALT + 124 ||
                if(archivo.getName().endsWith("xls")||archivo.getName().endsWith("xlsx")){
                    objEntidad = objDataImportar.Importar(archivo,this.jTableUniversal);
                    objBLImportarData.obtenerClavesCandidatas(jTableClavesCandidatas, objEntidad);
                    this.arrayClavesCandidatas = objEntidad.getAtributos();
                    this.numClavesCandidatas = this.arrayClavesCandidatas.size();
                    activarComponentes();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Seleccionar formato Valido");
                }
            }
    }//GEN-LAST:event_btnImportarActionPerformed

    private void jButtonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElegirActionPerformed
        // TODO add your handling code here:
        objAuxEntidad = objEntidad;
        if (this.numClavesCandidatas !=0){
            if(this.jTableClavesCandidatas.getSelectedRow() >= 0){
                this.arrayClavesPrimarias.add(this.arrayClavesCandidatas.get(this.jTableClavesCandidatas.getSelectedRow()));
                this.numClavesPrimarias = this.arrayClavesPrimarias.size();
                objBLImportarData.establecerClavesPrimarias(this.jTableClavesPrimarias,this.arrayClavesPrimarias);
                this.arrayClavesCandidatas.remove(this.jTableClavesCandidatas.getSelectedRow());
                this.numClavesCandidatas = this.arrayClavesCandidatas.size();
                objBLImportarData.establecerClavesCandidatas(jTableClavesCandidatas, arrayClavesCandidatas);
                //System.out.println("Clave candidata: "+ objEntidad.getAtributos().get((this.jTableClavesCandidatas.getSelectedRow() + numAtributoCandidato) + 1));
            }else{
                JOptionPane.showMessageDialog(null, "Debe elegir alguna clave candidata");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No existen claves candidatas");
        }
        
        
    }//GEN-LAST:event_jButtonElegirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if (this.numClavesPrimarias !=0){
            if(this.jTableClavesPrimarias.getSelectedRow() >= 0){
                this.arrayClavesCandidatas.add(this.arrayClavesPrimarias.get(this.jTableClavesPrimarias.getSelectedRow()));
                this.numClavesCandidatas = this.arrayClavesCandidatas.size();
                objBLImportarData.establecerClavesCandidatas(this.jTableClavesCandidatas,this.arrayClavesCandidatas);
                this.arrayClavesPrimarias.remove(this.jTableClavesPrimarias.getSelectedRow());
                this.numClavesPrimarias = this.arrayClavesPrimarias.size();
                objBLImportarData.establecerClavesPrimarias(jTableClavesPrimarias, arrayClavesPrimarias);
                
                //System.out.println("Clave candidata: "+ objEntidad.getAtributos().get((this.jTableClavesCandidatas.getSelectedRow() + numAtributoCandidato) + 1));
            }else{
                JOptionPane.showMessageDialog(null, "Debe elegir alguna clave primaria");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No existen claves primarias");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldNombreEntidad.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Ingrese por favor un nombre a la Entidad");
        else{
            if(this.numClavesPrimarias == 0)
                JOptionPane.showMessageDialog(null, "Debe selccionar al menos 1 clave primaria");
            else{
                if(objBLAtributo.validarClavePrimaria(this.arrayClavesPrimarias)){
                    objEntidad.setNombre(this.jTextFieldNombreEntidad.getText());
                    GLOBAL.GlobalVariables.entidadUniversal = objEntidad;
                    GUIPrimeraFormaNormal objGUIPrimeraFormaNormal = new GUIPrimeraFormaNormal(this.arrayClavesPrimarias);
                    objGUIPrimeraFormaNormal.setVisible(true);
                    this.setVisible(false);  
                }else{
                    JOptionPane.showMessageDialog(null, "Los atributos seleccionados no pueden ser claves primarias, "
                            + "pruebe con una clave compuesta");
                }
            }
        }
        
    }//GEN-LAST:event_jButtonSiguienteActionPerformed
    
    public void activarComponentes(){
        this.jTextFieldNombreEntidad.setEnabled(true);
        this.jButtonElegir.setEnabled(true);
        this.jButtonEliminar.setEnabled(true);
        this.jButtonSiguiente.setEnabled(true);
        this.jTableClavesCandidatas.setEnabled(true);
        this.jTableClavesPrimarias.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIImportarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIImportarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIImportarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIImportarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIImportarData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnImportar;
    private javax.swing.JButton jButtonElegir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEntidadUniversal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableClavesCandidatas;
    private javax.swing.JTable jTableClavesPrimarias;
    public javax.swing.JTable jTableUniversal;
    private javax.swing.JTextField jTextFieldNombreEntidad;
    // End of variables declaration//GEN-END:variables
}
